### ISSUE TITLE
Piccolo return type

### ISSUE THREAD

**Issue by sinisaos** [sayanarijit/bench#2]
Hello again and sorry to bother you. Just a few tips about the Piccolo types. I know it's not particularly important for benchmark tests, but I saw you made a PR in the Piccolo repo that might not be needed (the maintainer will decide about that). A little tip is to run `./scripts/lint.sh`  from root and a few files and tests that you need to fix in order for PR to pass the linter checks. Check in [contribution docs](https://piccolo-orm.readthedocs.io/en/latest/piccolo/contributing/index.html).

As for this repo, Piccolo automatically creates a primary key and you don't need to specify an `id` column, but then you have to use `TaskPiccolo._meta.primary_key` in your queries to keep Mypy happy. If a primary key is specified (as in your case), you just need to add a `Serial` type hint to the `id` column, like this
```python
class TaskPiccolo(PiccoloTable, tablename="task"):
    id: picols.Serial = picols.Serial(primary_key=True)
    name = picols.Varchar()
    completed = picols.Boolean()
```
and then you can use `TaskPiccolo.id` in queries and Mypy won't return errors.

https://github.com/sayanarijit/bench/blob/7de9111130116e2bd4e27ec5788b7f93e51541a6/app.py#L135

You don't need to specify a `list()` because a multi-result query is already a `list`.

https://github.com/sayanarijit/bench/blob/7de9111130116e2bd4e27ec5788b7f93e51541a6/app.py#L141-L142

In Piccolo if you want a single result as a `dict`, you just need to specify the `first()` clause in the query and then you don't need `result[0]` but only a `result` like this

```python
result = await TaskPiccolo.select().where(TaskPiccolo.id == id).first().run()
return result
```

**Comment by sayanarijit** [comment]
Thank you for your inputs again. These are really helpful in learning piccolo.

> A little tip is to run ./scripts/lint.sh from root and a few files and tests that you need to fix in order for PR to pass the linter checks

I think if there is any linting error, that would mean there maybe some bug lying there. I'm not yet familiar enough with the codebase to suggest bug fixes as of now. So I'd leave it to the maintainer.

> you just need to add a Serial type hint to the id column, like this

Can you please explain why this is the case? Just `id = picols.Serial(primary_key=True)` works well, there's no linting issue.

`first().run()` is a bit unintuitive, as I'm accustomed to `run().first()` styled APIs. ~I wonder why this would be the case.~ I guess it’s because sqla returns an object while peewee and piccolo returns list. But unlike piccolo, peewee doesn’t have to respect the type system, so it returns anything.

I have updated the code based on your suggestions. Thank you again for your time.

**Comment by sinisaos** [comment]
> Can you please explain why this is the case? Just `id = picols.Serial(primary_key=True)` works well, there's no linting issue.
> 

You're actually right. When I install the latest version of mypy (I have that problem with older mypy version) **there is no need to** type hint `id` column. Sorry my mistake.

> `first().run()` is a bit unintuitive, as I'm accustomed to `run().first()` styled APIs. ~I wonder why this would be the case.~ I guess it’s because sqla returns an object while peewee and piccolo returns list. But unlike piccolo, peewee doesn’t have to respect the type system, so it returns anything.
> 

You don't actually even need to use the `run()` method in your async queries (for synchronous queries you have to explicitly declare a `run_sync()` method to run the query) because of the magic `__await__` method on the [Query class](https://github.com/piccolo-orm/piccolo/blob/00fb487341237f4b5557874e0d6dbb53d9c6226f/piccolo/query/base.py#L90-L95).
I agree that these are personal preferences and you can use any of these queries as you wish, they are all valid.

```python
result = await TaskPiccolo.select().where(TaskPiccolo.id == id).first().run()
result = await TaskPiccolo.select().where(TaskPiccolo.id == id).first()
return result
# OR 
result = await TaskPiccolo.select().where(TaskPiccolo.id == id).run()
result = await TaskPiccolo.select().where(TaskPiccolo.id == id)
return result[0]
```

> I have updated the code based on your suggestions. Thank you again for your time.

No problem. I'm glad if I can somehow help.
